sudo: false
language: python
cache: pip
dist: bionic

branches:
  only:
    - master

script:
  - tox

install:
  - pip install tox

matrix:
  include:
    - python: "3.4"
      env: TOXENV=py34-django111
    - python: "3.5"
      env: TOXENV=py35-django111
    - python: "3.6"
      env: TOXENV=py36-django111
    - python: "3.4"
      env: TOXENV=py34-django20
    - python: "3.5"
      env: TOXENV=py35-django20
    - python: "3.6"
      env: TOXENV=py36-django20
    - python: "3.7"
      env: TOXENV=py37-django20

    # Linting
    - python: "3.7"
      env: TOXENV=lint
    # Test dev makefile
    - python: "3.7"
      env: TOXENV=dev
    # Check default production settings
    - python: "3.7"
      env: TOXENV=prodsettings

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#platal"
    on_success: change
    on_failure: always
    use_notice: true
