# Generated by Django 2.0.7 on 2018-07-10 22:32

from django.db import migrations, models
import django.db.models.deletion
import xorgdata.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma_reference', xorgdata.utils.fields.UnboundedCharField()),
                ('diplomed', models.BooleanField()),
                ('diplomation_date', models.DateField()),
                ('cycle', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('domain', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('name', xorgdata.utils.fields.UnboundedCharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('af_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ax_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('first_name', xorgdata.utils.fields.UnboundedCharField()),
                ('last_name', xorgdata.utils.fields.UnboundedCharField()),
                ('common_name', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('civility', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('address_1', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('address_2', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('address_3', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('address_4', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('address_postcode', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('address_city', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('address_state', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('address_country', models.CharField(blank=True, max_length=2)),
                ('address_npai', models.NullBooleanField()),
                ('phone_personnal', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('phone_mobile', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254)),
                ('nationality', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('nationality_2', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('nationality_3', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('dead', models.NullBooleanField()),
                ('deathdate', models.DateField(blank=True, null=True)),
                ('dead_for_france', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('user_kind', models.IntegerField()),
                ('additional_roles', models.IntegerField(blank=True, null=True)),
                ('xorg_id', xorgdata.utils.fields.DottedSlugField(max_length=255, unique=True)),
                ('school_id', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('admission_path', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('cursus_domain', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('cursus_name', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('corps_current', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('corps_origin', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('corps_grade', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('nickname', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('sport_section', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('binets', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('mail_reception', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('newsletter_inscriptions', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('profile_picture_url', xorgdata.utils.fields.UnboundedCharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionnalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', xorgdata.utils.fields.UnboundedCharField()),
                ('role', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('company_name', xorgdata.utils.fields.UnboundedCharField()),
                ('address_1', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('address_2', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('address_3', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('address_4', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('address_postcode', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('address_city', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('address_country', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('phone_indicator', models.IntegerField(blank=True)),
                ('phone_number', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('mobile_phone_indicator', models.IntegerField(blank=True)),
                ('mobile_phone_number', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('fax', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_kind', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('current', models.NullBooleanField()),
                ('creator_of_company', models.NullBooleanField()),
                ('buyer_of_company', models.NullBooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnforce.Account')),
            ],
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnforce.Account'),
        ),
    ]
