# Generated by Django 2.0.10 on 2019-03-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnforce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionnalinformation',
            name='mobile_phone_indicator',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionnalinformation',
            name='phone_indicator',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
