# Generated by Django 2.0.7 on 2018-07-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnforce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='entry_way',
            new_name='admission_path',
        ),
    ]
