# Generated by Django 2.0.10 on 2019-03-23 18:49

from django.db import migrations, models
import django.db.models.deletion
import xorgdata.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alumnforce', '0002_make_integer_fields_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('af_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ax_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('url', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('name', xorgdata.utils.fields.UnboundedCharField(blank=True)),
                ('category', xorgdata.utils.fields.UnboundedCharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMemberhip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SlugField(choices=[
                    ('banned', 'banned'),
                    ('invited', 'invited'),
                    ('member', 'member'),
                    ('moderator', 'moderator'),
                    ('onlist', 'on list'),
                    ('responsible', 'responsible'),
                    ('unsubscribed', 'unsubscribed')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnforce.Account')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnforce.Group')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='groupmemberhip',
            unique_together={('group', 'account')},
        ),
    ]
