# Generated by Django 2.0.10 on 2019-03-23 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumnforce', '0003_create_group_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinformation',
            name='last_update',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='last_update',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='last_update',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmemberhip',
            name='last_update',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionnalinformation',
            name='last_update',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
