# Generated by Django 2.0.10 on 2019-04-15 20:42

from django.db import migrations
import xorgdata.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alumnforce', '0005_add_log_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='xorg_id',
            field=xorgdata.utils.fields.DottedSlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
