# Generated by Django 2.0.10 on 2019-04-15 21:04

import django.core.validators
from django.db import migrations
import re
import xorgdata.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alumnforce', '0006_make_xorg_id_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='additional_roles',
            field=xorgdata.utils.fields.UnboundedCharField(
                blank=True, default='',
                validators=[django.core.validators.RegexValidator(
                    re.compile('^\\d+(?:,\\d+)*\\Z'),
                    code='invalid',
                    message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
    ]
