# Generated by Django 2.0.10 on 2019-04-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnforce', '0007_make_roles_a_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='export_kind',
            field=models.SlugField(choices=[
                ('users', 'users'),
                ('groups', 'groups'),
                ('groupmembers', 'groupmembers'),
                ('userdegrees', 'userdegrees'),
                ('userjobs', 'userjobs')
            ]),
        ),
    ]
