# Generated by Django 2.0.10 on 2019-04-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnforce', '0009_remove_unique_user_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinformation',
            name='diplomation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinformation',
            name='diplomed',
            field=models.NullBooleanField(),
        ),
    ]
