# Generated by Django 2.2 on 2019-04-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnforce', '0010_allow_null_fields_in_userdegree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinformation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees',
                                    to='alumnforce.Account'),
        ),
        migrations.AlterField(
            model_name='groupmemberhip',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships',
                                    to='alumnforce.Account'),
        ),
        migrations.AlterField(
            model_name='groupmemberhip',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships',
                                    to='alumnforce.Group'),
        ),
        migrations.AlterField(
            model_name='professionnalinformation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs',
                                    to='alumnforce.Account'),
        ),
    ]
