# Generated by Django 2.2 on 2019-04-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnforce', '0011_name_related_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMemberhip',
            new_name='GroupMembership',
        ),
    ]
