# Generated by Django 2.2 on 2019-06-30 15:20

from django.db import migrations, models
import xorgdata.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alumnforce', '0013_support_deleted_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('export_kind', models.SlugField(choices=[('auth', 'X.org auth')])),
                ('error', models.IntegerField(choices=[(0, 'success')])),
                ('num_items', models.IntegerField(blank=True, null=True)),
                ('message', xorgdata.utils.fields.UnboundedCharField(blank=True)),
            ],
        ),
    ]
