# Generated by Django 5.2.13 on 2026-05-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnforce', '0014_add_exportlog_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinformation',
            name='diplomed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinformation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='address_npai',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='dead',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exportlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='professionnalinformation',
            name='buyer_of_company',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionnalinformation',
            name='creator_of_company',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionnalinformation',
            name='current',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionnalinformation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
