from django.db import models

from xorgdata.utils.fields import DottedSlugField, UnboundedCharField

# Create your models here.
class Account(models.Model):
    af_id = models.IntegerField(primary_key=True)
    ax_id = models.CharField(max_length=20, blank=True, null=True, unique=True)
    firstname = UnboundedCharField()
    lastname = UnboundedCharField()
    commonname = UnboundedCharField(blank=True)
    civility = UnboundedCharField(blank=True)
    birthdate = models.DateField()
    address_1 = UnboundedCharField(blank=True)
    address_2 = UnboundedCharField(blank=True)
    address_3 = UnboundedCharField(blank=True)
    address_4 = UnboundedCharField(blank=True)
    address_postcode = UnboundedCharField(blank=True)
    address_city = UnboundedCharField(blank=True)
    address_state = UnboundedCharField(blank=True)
    address_country = models.CharField(max_length=2, blank=True)
    address_npai = models.NullBooleanField()
    phone_personnal = UnboundedCharField(blank=True)
    phone_mobile = UnboundedCharField(blank=True)
    email1 = models.EmailField()
    email2 = models.EmailField(blank=True)
    nationality = UnboundedCharField(blank=True)
    nationality2 = UnboundedCharField(blank=True)
    nationality3 = UnboundedCharField(blank=True)
    dead = models.NullBooleanField()
    deathdate = models.DateField(blank=True, null=True)
    dead_for_france = UnboundedCharField(blank=True)
    user_kind = models.IntegerField()
    additional_roles = models.IntegerField()
    xorg_id = DottedSlugField(unique=True, max_length=255)
    school_id = UnboundedCharField(blank=True)
    admission_path = UnboundedCharField(blank=True)
    cursus_domain = UnboundedCharField(blank=True)
    cursus_name = UnboundedCharField(blank=True)
    current_corps = UnboundedCharField(blank=True)
    origin_corps = UnboundedCharField(blank=True)
    grade = UnboundedCharField(blank=True)
    surname = UnboundedCharField(blank=True)
    sport_section = UnboundedCharField(blank=True)
    binets = UnboundedCharField(blank=True)
    mail_reception = UnboundedCharField(blank=True)
    newsletter_inscription = UnboundedCharField(blank=True)
    profile_picture_url = UnboundedCharField(blank=True)

class AcademicInformation(models.Model):
    account = models.ForeignKey('Account', on_delete=models.CASCADE)
    diploma_reference = UnboundedCharField()
    diplomed = models.BooleanField()
    diplomation_date = models.DateField()
    cycle = UnboundedCharField(blank=True)
    domain = UnboundedCharField(blank=True)
    name = UnboundedCharField(blank=True)

class ProfessionnalInformation(models.Model):
    account = models.ForeignKey('Account', on_delete=models.CASCADE)
    title = UnboundedCharField()
    role = UnboundedCharField(blank=True)
    company_name = UnboundedCharField()
    address_1 = UnboundedCharField(blank=True)
    address_2 = UnboundedCharField(blank=True)
    address_3 = UnboundedCharField(blank=True)
    address_4 = UnboundedCharField(blank=True)
    address_postcode = UnboundedCharField(blank=True)
    address_city = UnboundedCharField(blank=True)
    address_country = UnboundedCharField(blank=True)
    phone_indicator = models.IntegerField(blank=True)
    phone_number = UnboundedCharField(blank=True)
    mobile_phone_indicator = models.IntegerField(blank=True)
    mobile_phone_number = UnboundedCharField(blank=True)
    fax = UnboundedCharField(blank=True)
    email = models.EmailField(blank=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    contract_kind = UnboundedCharField(blank=True)
    current = models.NullBooleanField()
    creator_of_company = models.NullBooleanField()
    buyer_of_company = models.NullBooleanField()
